version: '3'
services:
  php-fpm:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    user: "1000"
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - .:/var/www
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./docker/nginx-sites:/etc/nginx/conf.d
      - .:/var/www
    ports:
      - 80:80
      - 443:443
    links:
      - php-fpm
